FROM python:3.12-slim

RUN pip install --no-cache-dir ansible && \
    apt-get update && apt-get install -y sshpass openssh-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ansible

# Copy playbooks directly into /ansible
COPY ansible/ .

#CMD ["ansible-playbook", "-i", "inventory", "deploy.yml"]
